#!/usr/bin/env python3
"""Turn the Unicorns app's pixel art into freeink::Icon structs.

    python3 tools_local/unicorns/gen_art.py

Reads every *.txt beside this script ('#' is ink, anything else is paper) and
writes src/apps_local/unicorns/UnicornArt.h. Lucide has no unicorn, so the art
is drawn here by hand; the header is committed so a checkout builds without
running this.
"""
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent.parent / "src" / "apps_local" / "unicorns" / "UnicornArt.h"


def encode(name, rows):
    width = max(len(r) for r in rows)
    rows = [r.ljust(width, ".") for r in rows]
    data = []
    ink_rows = []
    for y, row in enumerate(rows):
        for start in range(0, width, 8):
            byte = 0
            for bit in range(8):
                x = start + bit
                paper = x >= width or row[x] != "#"
                if paper:
                    byte |= 0x80 >> bit
            data.append(byte)
        ink_rows.extend([y] * row.count("#"))
    centre = round(sum(ink_rows) / len(ink_rows)) if ink_rows else len(rows) // 2
    lines = [f"// {name}, {width}x{len(rows)}, from tools_local/unicorns/{name}.txt"]
    lines.append(f"static const uint8_t art_{name}_bits[] = {{")
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
    lines.append("};")
    lines.append(
        f"static const freeink::Icon art_{name} = {{{width}, {len(rows)}, {centre}, art_{name}_bits}};")
    return "\n".join(lines)


def main():
    parts = [
        "#pragma once",
        "",
        "// Generated by tools_local/unicorns/gen_art.py. Edit the .txt art, not this.",
        "",
        "#include \"Icon.h\"",
        "",
        "#include <cstdint>",
        "",
    ]
    for path in sorted(HERE.glob("*.txt")):
        rows = [l.rstrip("\n") for l in path.read_text().splitlines() if l.strip()]
        parts.append(encode(path.stem, rows))
        parts.append("")
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
